/** Client-side export helpers for workflow version diffs. */

export function downloadWorkflowDiffJson(versionDiff, workflowName = "workflow") {
  if (!versionDiff) return;
  const { from_graph, to_graph, overlay, ...rest } = versionDiff;
  const payload = {
    workflow_name: workflowName,
    exported_at: new Date().toISOString(),
    ...rest,
    summary: versionDiff.summary,
    nodes_added: versionDiff.nodes_added,
    nodes_removed: versionDiff.nodes_removed,
    nodes_changed: versionDiff.nodes_changed,
    edges_added: versionDiff.edges_added,
    edges_removed: versionDiff.edges_removed,
  };
  triggerDownload(
    JSON.stringify(payload, null, 2),
    buildDiffFilename(workflowName, versionDiff.from, versionDiff.to, "json"),
    "application/json"
  );
}

export function downloadWorkflowDiffMarkdown(versionDiff, workflowName = "workflow") {
  if (!versionDiff) return;
  const lines = [
    `# ${workflowName} — version diff`,
    "",
    `**Compare:** \`${versionDiff.from}\` → \`${versionDiff.to}\``,
    "",
    "## Summary",
    "",
    `- Nodes added: **${versionDiff.summary?.nodes_added || 0}**`,
    `- Nodes removed: **${versionDiff.summary?.nodes_removed || 0}**`,
    `- Nodes changed: **${versionDiff.summary?.nodes_changed || 0}**`,
    `- Edges added: **${versionDiff.summary?.edges_added || 0}**`,
    `- Edges removed: **${versionDiff.summary?.edges_removed || 0}**`,
    "",
  ];

  const sections = [
    ["Nodes added", versionDiff.nodes_added, (n) => `- \`${n.id}\` **${n.type}** — ${n.label || "—"}`],
    ["Nodes removed", versionDiff.nodes_removed, (n) => `- \`${n.id}\` **${n.type}** — ${n.label || "—"}`],
    [
      "Nodes changed",
      versionDiff.nodes_changed,
      (c) =>
        `- \`${c.id}\` **${c.type}**: ${c.before?.label || "—"} → ${c.after?.label || "—"}`,
    ],
    ["Edges added", versionDiff.edges_added, (e) => `- \`${e.from}\` → \`${e.to}\``],
    ["Edges removed", versionDiff.edges_removed, (e) => `- \`${e.from}\` → \`${e.to}\``],
  ];

  for (const [title, items, fmt] of sections) {
    if (!items?.length) continue;
    lines.push(`## ${title}`, "");
    items.forEach((item) => lines.push(fmt(item)));
    lines.push("");
  }

  lines.push("---", "*Generated by NovaFlow AI*", "");
  triggerDownload(
    lines.join("\n"),
    buildDiffFilename(workflowName, versionDiff.from, versionDiff.to, "md"),
    "text/markdown"
  );
}

function buildDiffFilename(name, from, to, ext) {
  const safe = (name || "workflow").replace(/[^\w.-]+/g, "-").slice(0, 40);
  const fromSafe = (from || "from").replace(/[^\w.-]+/g, "-");
  const toSafe = (to || "to").replace(/[^\w.-]+/g, "-");
  return `novaflow-diff-${safe}-${fromSafe}-to-${toSafe}.${ext}`;
}

function triggerDownload(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}
