import json
from typing import Any


def _graph_maps(graph: dict) -> tuple[dict[str, dict], list[dict]]:
    nodes = {n["id"]: n for n in graph.get("nodes", []) if n.get("id")}
    edges = graph.get("edges") or []
    return nodes, edges


def _edge_key(edge: dict) -> str:
    return f"{edge.get('from')}->{edge.get('to')}"


def _node_summary(node: dict) -> dict:
    data = node.get("data") or {}
    return {
        "id": node.get("id"),
        "type": node.get("type"),
        "label": data.get("label") or data.get("prompt", "")[:40] or node.get("type"),
    }


def diff_workflow_graphs(old_graph: dict, new_graph: dict) -> dict[str, Any]:
    old_nodes, old_edges = _graph_maps(old_graph)
    new_nodes, new_edges = _graph_maps(new_graph)

    old_edge_keys = {_edge_key(e) for e in old_edges}
    new_edge_keys = {_edge_key(e) for e in new_edges}

    nodes_added = [_node_summary(new_nodes[nid]) for nid in new_nodes if nid not in old_nodes]
    nodes_removed = [_node_summary(old_nodes[nid]) for nid in old_nodes if nid not in new_nodes]
    nodes_changed = []
    for nid in old_nodes:
        if nid in new_nodes and json.dumps(old_nodes[nid], sort_keys=True) != json.dumps(new_nodes[nid], sort_keys=True):
            nodes_changed.append(
                {
                    "id": nid,
                    "type": new_nodes[nid].get("type"),
                    "before": _node_summary(old_nodes[nid]),
                    "after": _node_summary(new_nodes[nid]),
                }
            )

    edges_added = [e for e in new_edges if _edge_key(e) not in old_edge_keys]
    edges_removed = [e for e in old_edges if _edge_key(e) not in new_edge_keys]

    removed_full = [old_nodes[nid] for nid in old_nodes if nid not in new_nodes]

    return {
        "summary": {
            "nodes_added": len(nodes_added),
            "nodes_removed": len(nodes_removed),
            "nodes_changed": len(nodes_changed),
            "edges_added": len(edges_added),
            "edges_removed": len(edges_removed),
        },
        "nodes_added": nodes_added,
        "nodes_removed": nodes_removed,
        "nodes_changed": nodes_changed,
        "edges_added": edges_added,
        "edges_removed": edges_removed,
        "overlay": {
            "added_ids": [n["id"] for n in nodes_added],
            "changed_ids": [c["id"] for c in nodes_changed],
            "removed_nodes": removed_full,
            "edges_added": edges_added,
            "edges_removed": edges_removed,
        },
    }


def format_diff_markdown(
    diff: dict[str, Any],
    *,
    workflow_name: str = "",
    from_label: str = "",
    to_label: str = "",
) -> str:
    """Human-readable markdown report for workflow version comparisons."""
    title = workflow_name or "Workflow"
    header = f"# {title} — version diff\n\n"
    if from_label and to_label:
        header += f"**Compare:** `{from_label}` → `{to_label}`\n\n"

    summary = diff.get("summary") or {}
    lines = [
        header,
        "## Summary\n",
        f"- Nodes added: **{summary.get('nodes_added', 0)}**",
        f"- Nodes removed: **{summary.get('nodes_removed', 0)}**",
        f"- Nodes changed: **{summary.get('nodes_changed', 0)}**",
        f"- Edges added: **{summary.get('edges_added', 0)}**",
        f"- Edges removed: **{summary.get('edges_removed', 0)}**",
        "",
    ]

    added = diff.get("nodes_added") or []
    if added:
        lines.append("## Nodes added\n")
        for n in added:
            lines.append(f"- `{n.get('id')}` **{n.get('type')}** — {n.get('label') or '—'}")
        lines.append("")

    removed = diff.get("nodes_removed") or []
    if removed:
        lines.append("## Nodes removed\n")
        for n in removed:
            lines.append(f"- `{n.get('id')}` **{n.get('type')}** — {n.get('label') or '—'}")
        lines.append("")

    changed = diff.get("nodes_changed") or []
    if changed:
        lines.append("## Nodes changed\n")
        for c in changed:
            before = c.get("before") or {}
            after = c.get("after") or {}
            lines.append(
                f"- `{c.get('id')}` **{c.get('type')}**: "
                f"{before.get('label') or '—'} → {after.get('label') or '—'}"
            )
        lines.append("")

    edges_added = diff.get("edges_added") or []
    if edges_added:
        lines.append("## Edges added\n")
        for e in edges_added:
            lines.append(f"- `{e.get('from')}` → `{e.get('to')}`")
        lines.append("")

    edges_removed = diff.get("edges_removed") or []
    if edges_removed:
        lines.append("## Edges removed\n")
        for e in edges_removed:
            lines.append(f"- `{e.get('from')}` → `{e.get('to')}`")
        lines.append("")

    lines.append("---\n*Generated by NovaFlow AI*\n")
    return "\n".join(lines)
